import type { DeviceCategory } from "@/canvas/device"
import netboxData from "./netbox-catalog.json"

export interface CatalogDevice {
  catalogId: string
  name: string
  manufacturer: string
  model: string
  uHeight: number
  isFullDepth: boolean
  powerWatts: number
  weightKg: number
  category: DeviceCategory
  frontImageUrl: string | null
  rearImageUrl: string | null
}

// --- NetBox catalog (generated by scripts/import-netbox-catalog.ts) ---

interface NetBoxEntry {
  manufacturer: string
  model: string
  slug: string
  uHeight: number
  isFullDepth: boolean
  weightKg: number | null
  maxPowerWatts: number | null
  category: string
  frontImageUrl: string | null
  rearImageUrl: string | null
}

const VALID_CATEGORIES = new Set<string>([
  "server", "switch", "patch_panel", "pdu", "storage", "ups", "blank", "other",
])

const _netboxCatalog: CatalogDevice[] = (netboxData.devices as NetBoxEntry[]).map((d) => ({
  catalogId: `nb-${d.slug}`,
  name: d.model,
  manufacturer: d.manufacturer,
  model: d.model,
  uHeight: d.uHeight,
  isFullDepth: d.isFullDepth,
  powerWatts: d.maxPowerWatts ?? 0,
  weightKg: d.weightKg ?? 0,
  category: (VALID_CATEGORIES.has(d.category) ? d.category : "other") as DeviceCategory,
  frontImageUrl: d.frontImageUrl ?? null,
  rearImageUrl: d.rearImageUrl ?? null,
}))

/** Static fallback catalog — used when netbox-catalog.json has no devices. */
const BUILTIN_DEVICES: CatalogDevice[] = ([
  // Servers
  { catalogId: "dell-r660", name: "PowerEdge R660", manufacturer: "Dell", model: "R660", uHeight: 1, isFullDepth: true, powerWatts: 700, weightKg: 18, category: "server" },
  { catalogId: "dell-r760", name: "PowerEdge R760", manufacturer: "Dell", model: "R760", uHeight: 2, isFullDepth: true, powerWatts: 1100, weightKg: 28, category: "server" },
  { catalogId: "dell-r960", name: "PowerEdge R960", manufacturer: "Dell", model: "R960", uHeight: 4, isFullDepth: true, powerWatts: 2200, weightKg: 45, category: "server" },
  { catalogId: "hpe-dl360", name: "ProLiant DL360", manufacturer: "HPE", model: "DL360 Gen11", uHeight: 1, isFullDepth: true, powerWatts: 800, weightKg: 19, category: "server" },
  { catalogId: "hpe-dl380", name: "ProLiant DL380", manufacturer: "HPE", model: "DL380 Gen11", uHeight: 2, isFullDepth: true, powerWatts: 1200, weightKg: 30, category: "server" },
  { catalogId: "sm-1u", name: "SuperServer 1U", manufacturer: "Supermicro", model: "SYS-121H", uHeight: 1, isFullDepth: true, powerWatts: 600, weightKg: 16, category: "server" },

  // Switches
  { catalogId: "cisco-9300", name: "Catalyst 9300", manufacturer: "Cisco", model: "C9300-48T", uHeight: 1, isFullDepth: false, powerWatts: 120, weightKg: 6, category: "switch" },
  { catalogId: "cisco-nexus-9336", name: "Nexus 9336C", manufacturer: "Cisco", model: "N9K-C9336C", uHeight: 1, isFullDepth: false, powerWatts: 250, weightKg: 8, category: "switch" },
  { catalogId: "arista-7050", name: "7050SX3-48YC8", manufacturer: "Arista", model: "7050SX3", uHeight: 1, isFullDepth: false, powerWatts: 200, weightKg: 7, category: "switch" },
  { catalogId: "juniper-ex4400", name: "EX4400-48T", manufacturer: "Juniper", model: "EX4400", uHeight: 1, isFullDepth: false, powerWatts: 150, weightKg: 6, category: "switch" },

  // Patch panels
  { catalogId: "panduit-cp24", name: "24-Port Cat6a", manufacturer: "Panduit", model: "CP24", uHeight: 1, isFullDepth: false, powerWatts: 0, weightKg: 1, category: "patch_panel" },
  { catalogId: "panduit-cp48", name: "48-Port Cat6a", manufacturer: "Panduit", model: "CP48", uHeight: 2, isFullDepth: false, powerWatts: 0, weightKg: 2, category: "patch_panel" },
  { catalogId: "leviton-fp24", name: "24-Port Fiber", manufacturer: "Leviton", model: "5F100-2FL", uHeight: 1, isFullDepth: false, powerWatts: 0, weightKg: 1, category: "patch_panel" },

  // PDUs
  { catalogId: "apc-pdu-basic", name: "Basic Rack PDU", manufacturer: "APC", model: "AP7900B", uHeight: 1, isFullDepth: false, powerWatts: 0, weightKg: 4, category: "pdu" },
  { catalogId: "apc-pdu-metered", name: "Metered Rack PDU", manufacturer: "APC", model: "AP8858", uHeight: 2, isFullDepth: false, powerWatts: 0, weightKg: 6, category: "pdu" },
  { catalogId: "raritan-px3", name: "PX3 iPDU", manufacturer: "Raritan", model: "PX3-5902V", uHeight: 1, isFullDepth: false, powerWatts: 0, weightKg: 5, category: "pdu" },

  // Storage
  { catalogId: "netapp-aff250", name: "AFF A250", manufacturer: "NetApp", model: "AFF A250", uHeight: 2, isFullDepth: true, powerWatts: 600, weightKg: 20, category: "storage" },
  { catalogId: "netapp-aff800", name: "AFF A800", manufacturer: "NetApp", model: "AFF A800", uHeight: 4, isFullDepth: true, powerWatts: 1500, weightKg: 40, category: "storage" },
  { catalogId: "synology-rs1221", name: "RS1221+", manufacturer: "Synology", model: "RS1221+", uHeight: 2, isFullDepth: true, powerWatts: 200, weightKg: 10, category: "storage" },

  // UPS
  { catalogId: "apc-srt2200", name: "Smart-UPS SRT 2200VA", manufacturer: "APC", model: "SRT2200", uHeight: 2, isFullDepth: true, powerWatts: 2200, weightKg: 32, category: "ups" },
  { catalogId: "apc-srt5000", name: "Smart-UPS SRT 5000VA", manufacturer: "APC", model: "SRT5000", uHeight: 3, isFullDepth: true, powerWatts: 5000, weightKg: 52, category: "ups" },
  { catalogId: "eaton-5px", name: "5PX 1500VA", manufacturer: "Eaton", model: "5PX1500RT", uHeight: 2, isFullDepth: true, powerWatts: 1500, weightKg: 22, category: "ups" },

  // Blanks
  { catalogId: "blank-1u", name: "Blank Panel 1U", manufacturer: "Generic", model: "BP-1U", uHeight: 1, isFullDepth: false, powerWatts: 0, weightKg: 0.5, category: "blank" },
  { catalogId: "blank-2u", name: "Blank Panel 2U", manufacturer: "Generic", model: "BP-2U", uHeight: 2, isFullDepth: false, powerWatts: 0, weightKg: 0.8, category: "blank" },
] as Omit<CatalogDevice, "frontImageUrl" | "rearImageUrl">[]).map((d) => ({ ...d, frontImageUrl: null, rearImageUrl: null }))

/** Full device catalog: NetBox community library if available, otherwise built-in fallbacks. */
export function getCatalogDevices(): CatalogDevice[] {
  if (_netboxCatalog.length > 0) return _netboxCatalog
  return BUILTIN_DEVICES
}

// --- Image URL lookup ---

let _imageUrlMap: Map<string, { front: string | null; rear: string | null }> | null = null

export function getDeviceImageUrl(catalogId: string, face: "front" | "rear"): string | null {
  if (!_imageUrlMap) {
    _imageUrlMap = new Map()
    for (const d of _netboxCatalog) {
      _imageUrlMap.set(d.catalogId, { front: d.frontImageUrl, rear: d.rearImageUrl })
    }
  }
  const entry = _imageUrlMap.get(catalogId)
  if (!entry) return null
  return face === "rear" ? entry.rear : entry.front
}

/**
 * @deprecated Use getCatalogDevices() instead. Kept for backward compatibility.
 */
export const CATALOG_DEVICES = BUILTIN_DEVICES
