import { optimize } from "svgo"
import { DEVICE_COLORS, type DeviceCategory } from "@/canvas/device"
import type { DeviceFace } from "@/store/rack-store"

// ─── Public types ────────────────────────────────────────────────

export interface ExportRack {
  id: string
  name: string
  uCount: number
  widthInches?: number
  startingUnit?: number
  descendingUnits?: boolean
}

export interface ExportDevice {
  id: string
  name: string
  manufacturer: string
  model: string
  uHeight: number
  isFullDepth: boolean
  startU: number
  category: DeviceCategory
  face?: DeviceFace
}

export interface ExportRackBundle {
  rack: ExportRack
  devices: ExportDevice[]
}

export interface SvgExportOptions {
  projectName?: string
  includeTitle?: boolean
}

// ─── Layout constants (px) ───────────────────────────────────────

const U_HEIGHT = 20
const RAIL_W = 24
const FACE_GAP = 40 // between front and rear of same rack
const PAIR_GAP = 80 // between different rack pairs
const PAD = 30
const TITLE_H = 44
const FACE_LABEL_H = 20
const NAME_LABEL_H = 22
const INDICATOR_W = 4

function rackWidthPx(widthInches?: number): number {
  return Math.round((widthInches ?? 19) / 19 * 300)
}

// ─── Print-friendly palette ──────────────────────────────────────

const P = {
  rackFill: "#f5f5fa",
  rackStroke: "#c0c0d0",
  gridLine: "#e0e0ec",
  uLabel: "#8888aa",
  deviceText: "#1a1a2e",
  deviceSub: "#666680",
  titleText: "#333344",
  subtitleText: "#888899",
  ghostOpacity: "0.3",
} as const

/** Lighter fills for print-friendly device bodies */
const PRINT_DEVICE_FILLS: Record<DeviceCategory, string> = {
  server: "#dbeafe",
  switch: "#dcfce7",
  patch_panel: "#fef9c3",
  pdu: "#fee2e2",
  storage: "#ede9fe",
  ups: "#ffedd5",
  blank: "#f3f4f6",
  other: "#f3f4f6",
}

// ─── Main SVG export ─────────────────────────────────────────────

export function exportSvg(
  racks: ExportRackBundle[],
  options: SvgExportOptions = {}
) {
  if (racks.length === 0) return undefined

  const svgContent = renderAllRacksSvg(racks, options)

  const result = optimize(svgContent, {
    multipass: true,
    plugins: [{
      name: "preset-default",
      params: { overrides: { convertShapeToPath: false, removeViewBox: false } },
    }],
  })

  const blob = new Blob([result.data], { type: "image/svg+xml" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${sanitize(options.projectName ?? "rack-layout")}-rack-layout.svg`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)

  return result.data
}

// ─── SVG renderers (also used by PDF export) ─────────────────────

/** Render all racks, each with front+rear side by side */
export function renderAllRacksSvg(
  racks: ExportRackBundle[],
  options: SvgExportOptions = {}
): string {
  const { projectName = "Rack Layout", includeTitle = true } = options
  const titleH = includeTitle ? TITLE_H : 0

  // Calculate total dimensions
  let totalW = 0
  let maxH = 0
  const pairWidths: number[] = []
  for (const { rack } of racks) {
    const rw = rackWidthPx(rack.widthInches)
    const pairW = (rw + RAIL_W) * 2 + FACE_GAP
    pairWidths.push(pairW)
    totalW += pairW
    const rackH = rack.uCount * U_HEIGHT + FACE_LABEL_H + NAME_LABEL_H
    if (rackH > maxH) maxH = rackH
  }
  totalW += (racks.length - 1) * PAIR_GAP

  const svgW = totalW + PAD * 2
  const svgH = maxH + PAD * 2 + titleH

  const parts: string[] = []

  // White background
  parts.push(rect(0, 0, svgW, svgH, "#ffffff"))

  // Title block
  if (includeTitle) {
    const date = new Date().toISOString().split("T")[0]
    parts.push(text(PAD, PAD + 16, `${escXml(projectName)} — ${date}`, {
      size: 14, fill: P.titleText, weight: "bold",
    }))
    parts.push(text(PAD, PAD + 32, "Generated by rackifai.com", {
      size: 10, fill: P.subtitleText,
    }))
  }

  // Render each rack pair
  let curX = PAD
  const contentTop = PAD + titleH
  for (let i = 0; i < racks.length; i++) {
    parts.push(renderRackPair(curX, contentTop, racks[i]))
    curX += pairWidths[i] + PAIR_GAP
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${svgW}" height="${svgH}" viewBox="0 0 ${svgW} ${svgH}">
${parts.join("\n")}
</svg>`
}

/** Render a single rack face (for PDF portrait pages) */
export function renderSingleFaceSvg(
  bundle: ExportRackBundle,
  face: DeviceFace,
  options: { rackLabel?: string; includeHeader?: boolean; projectName?: string } = {}
): string {
  const { rack } = bundle
  const rw = rackWidthPx(rack.widthInches)
  const rackH = rack.uCount * U_HEIGHT
  const headerH = options.includeHeader ? 40 : 0

  const contentW = rw + RAIL_W + 10
  const contentH = rackH + FACE_LABEL_H + NAME_LABEL_H
  const svgW = contentW + PAD * 2
  const svgH = contentH + PAD * 2 + headerH

  const parts: string[] = []
  parts.push(rect(0, 0, svgW, svgH, "#ffffff"))

  if (options.includeHeader) {
    parts.push(text(PAD, PAD + 14, options.rackLabel ?? rack.name, {
      size: 14, fill: P.titleText, weight: "bold",
    }))
    parts.push(text(PAD, PAD + 30, `${face.toUpperCase()} VIEW`, {
      size: 10, fill: P.subtitleText,
    }))
  }

  const x = PAD
  const y = PAD + headerH
  parts.push(renderFaceColumn(x, y, bundle, face))

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${svgW}" height="${svgH}" viewBox="0 0 ${svgW} ${svgH}">
${parts.join("\n")}
</svg>`
}

/** Render front+rear of one rack side by side (for PDF landscape pages) */
export function renderRackPairSvg(
  bundle: ExportRackBundle,
  options: { includeHeader?: boolean; projectName?: string } = {}
): string {
  const { rack } = bundle
  const rw = rackWidthPx(rack.widthInches)
  const rackH = rack.uCount * U_HEIGHT
  const headerH = options.includeHeader ? 40 : 0

  const pairW = (rw + RAIL_W) * 2 + FACE_GAP
  const contentH = rackH + FACE_LABEL_H + NAME_LABEL_H
  const svgW = pairW + PAD * 2
  const svgH = contentH + PAD * 2 + headerH

  const parts: string[] = []
  parts.push(rect(0, 0, svgW, svgH, "#ffffff"))

  if (options.includeHeader) {
    parts.push(text(PAD, PAD + 14, rack.name, {
      size: 14, fill: P.titleText, weight: "bold",
    }))
    parts.push(text(PAD, PAD + 30, "FRONT & REAR", {
      size: 10, fill: P.subtitleText,
    }))
  }

  parts.push(renderRackPair(PAD, PAD + headerH, bundle))

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${svgW}" height="${svgH}" viewBox="0 0 ${svgW} ${svgH}">
${parts.join("\n")}
</svg>`
}

// ─── Internal renderers ──────────────────────────────────────────

function renderRackPair(x: number, y: number, bundle: ExportRackBundle): string {
  const { rack } = bundle
  const rw = rackWidthPx(rack.widthInches)
  const pairW = (rw + RAIL_W) * 2 + FACE_GAP
  const rackH = rack.uCount * U_HEIGHT

  const parts: string[] = []

  // Rack name centered above the pair
  parts.push(text(x + pairW / 2, y + 14, rack.name, {
    size: 13, fill: P.titleText, weight: "bold", anchor: "middle",
  }))

  const colY = y + NAME_LABEL_H

  // Front column
  const frontX = x
  parts.push(text(frontX + (rw + RAIL_W) / 2, colY + 12, "FRONT", {
    size: 9, fill: P.subtitleText, anchor: "middle",
  }))
  parts.push(renderFaceColumn(frontX, colY + FACE_LABEL_H, bundle, "front"))

  // Rear column
  const rearX = x + rw + RAIL_W + FACE_GAP
  parts.push(text(rearX + (rw + RAIL_W) / 2, colY + 12, "REAR", {
    size: 9, fill: P.subtitleText, anchor: "middle",
  }))
  parts.push(renderFaceColumn(rearX, colY + FACE_LABEL_H, bundle, "rear"))

  // Thin divider line between front and rear
  const divX = x + rw + RAIL_W + FACE_GAP / 2
  parts.push(`<line x1="${divX}" y1="${colY + FACE_LABEL_H}" x2="${divX}" y2="${colY + FACE_LABEL_H + rackH}" stroke="#ddd" stroke-width="1" stroke-dasharray="4 4"/>`)

  return parts.join("\n")
}

function renderFaceColumn(x: number, y: number, bundle: ExportRackBundle, face: DeviceFace): string {
  const { rack, devices } = bundle
  const rw = rackWidthPx(rack.widthInches)
  const rackH = rack.uCount * U_HEIGHT
  const startU = rack.startingUnit ?? 1
  const desc = rack.descendingUnits ?? false

  const parts: string[] = []

  // Rack frame
  const frameX = x + RAIL_W
  parts.push(rect(frameX, y, rw, rackH, P.rackFill, P.rackStroke, 1))

  // Gridlines
  for (let i = 0; i <= rack.uCount; i++) {
    const gy = y + i * U_HEIGHT
    parts.push(`<line x1="${frameX}" y1="${gy}" x2="${frameX + rw}" y2="${gy}" stroke="${P.gridLine}" stroke-width="0.5"/>`)
  }

  // U-labels
  for (let i = 0; i < rack.uCount; i++) {
    const uNum = desc ? startU + i : startU + rack.uCount - 1 - i
    const ly = y + i * U_HEIGHT + U_HEIGHT / 2 + 3.5
    parts.push(text(x + RAIL_W - 4, ly, String(uNum), {
      size: 9, fill: P.uLabel, anchor: "end", family: "monospace",
    }))
  }

  // Devices
  const faceDevices = devices.filter(
    d => d.isFullDepth || (d.face ?? "front") === face
  )

  for (const dev of faceDevices) {
    const isGhost = !dev.isFullDepth && (dev.face ?? "front") !== face
    const devTopU = desc
      ? dev.startU - startU
      : rack.uCount - (dev.startU - startU) - dev.uHeight
    const devY = y + devTopU * U_HEIGHT
    const devH = dev.uHeight * U_HEIGHT
    const devX = frameX + 1
    const devW = rw - 2

    parts.push(renderDevice(devX, devY, devW, devH, dev, face, isGhost))
  }

  return parts.join("\n")
}

function renderDevice(
  x: number, y: number, w: number, h: number,
  dev: ExportDevice, viewFace: DeviceFace, isGhost: boolean
): string {
  const cat = dev.category
  const accentColor = DEVICE_COLORS[cat]
  const bodyFill = PRINT_DEVICE_FILLS[cat]
  const isRear = viewFace === "rear"

  const parts: string[] = []

  // Device body
  parts.push(rect(x, y, w, h, bodyFill, accentColor, 1, 2))

  // Category accent bar
  const barX = isRear ? x + w - INDICATOR_W : x
  parts.push(rect(barX, y, INDICATOR_W, h, accentColor))

  // Labels
  const textX = isRear ? x + 6 : x + INDICATOR_W + 6
  if (h >= 30) {
    // Multi-line: name + manufacturer/model
    parts.push(text(textX, y + 14, dev.name, {
      size: 11, fill: P.deviceText, weight: "bold",
    }))
    if (dev.manufacturer || dev.model) {
      const sub = [dev.manufacturer, dev.model].filter(Boolean).join(" ")
      parts.push(text(textX, y + 27, sub, {
        size: 8, fill: P.deviceSub,
      }))
    }
  } else {
    // Single line
    parts.push(text(textX, y + h / 2 + 3.5, dev.name, {
      size: 10, fill: P.deviceText, weight: "bold",
    }))
  }

  if (isGhost) {
    return `<g opacity="${P.ghostOpacity}">\n${parts.join("\n")}\n</g>`
  }
  return parts.join("\n")
}

// ─── SVG primitives ──────────────────────────────────────────────

function rect(
  x: number, y: number, w: number, h: number,
  fill: string, stroke?: string, strokeW?: number, rx?: number, opacity?: number
): string {
  let s = `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}"`
  if (stroke) s += ` stroke="${stroke}" stroke-width="${strokeW ?? 1}"`
  if (rx) s += ` rx="${rx}" ry="${rx}"`
  if (opacity != null) s += ` opacity="${opacity}"`
  return s + "/>"
}

interface TextOpts {
  size: number
  fill: string
  weight?: string
  anchor?: string
  family?: string
}

function text(x: number, y: number, content: string, o: TextOpts): string {
  let s = `<text x="${x}" y="${y}" font-size="${o.size}" fill="${o.fill}"`
  s += ` font-family="${o.family ?? "sans-serif"}"`
  if (o.weight) s += ` font-weight="${o.weight}"`
  if (o.anchor) s += ` text-anchor="${o.anchor}"`
  return s + `>${escXml(content)}</text>`
}

// ─── Helpers ─────────────────────────────────────────────────────

function escXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "-").toLowerCase()
}
